language: node_js
node_js:
- 6.9.5
cache:
  directories:
    - node_modules
dist: trusty
before_install:
  - npm install -g yarn
install:
  - yarn install
  - cd ./tests && yarn install && yarn install coveralls mocha-lcov-reporter && cd ..
after_success:
  - cd ./tests && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
  - tisto@plone.org, ebrehault@gmail.com, ramon.nb@gmail.com, sneridagh@gmail.com